[workspace]
authors = ["Andrew Sazonov <andrew.sazonov@icloud.com>"]
channels = ["conda-forge"]
name = "utils"
platforms = ["osx-arm64", "win-64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
copier = ">=9.11.3,<10"
